language: python
python:
  - "3.6.1"

install:
  - cp .env.template .env
  - mkdir .tmp
  - pip install -r requirements.dev.txt

script:
  - nosetests -a mode=simulated

after_success:
  - make html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: doc/_build
  committer-from-gh: true
  on:
    branch: dev


