language: python
python:
  - "3.6.5"

env:
  - DOCS_BRANCH=dev

install:
  - cp .env.template .env
  - mkdir .tmp
  - pip install pipenv
  - pipenv sync --dev

script:
  - pipenv run pytest -k simulated

after_success:
  - pipenv run make html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: doc/_build/html
  committer-from-gh: true
  on:
    branch: $DOCS_BRANCH

