language: python
python:
  - "3.6.1"

env:
  - DOCS_BRANCH=dev

install:
  - cp .env.template .env
  - mkdir .tmp
  - pipenv install

script:
  - pipenv run pytest -k simulated

after_success:
  - make html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: doc/_build/html
  committer-from-gh: true
  on:
    branch: $DOCS_BRANCH

