'''
Distributed Transactions in DistZero.

Each transaction exists not as a single python object, but as a collection
of related `TransactionRole` instances, each living on its own `Node`
'''

import asyncio
from collections import defaultdict

import dist_zero.logging
from dist_zero import messages, ids, errors


class TransactionRoleController(object):
  '''
  Controller object to allow `TransactionRole` instances to interact with the overall transaction.
  '''

  def __init__(self, node: 'dist_zero.node.node.Node', transaction_id: str):
    self.node = node
    self.transaction_id = transaction_id

    self.logger = dist_zero.logging.LoggerAdapter(
        self.node.logger, extra={
            'cur_node_id': self.node.id,
            'transaction_id': self.transaction_id,
        })

    self._matcher = _Matcher()

  def new_handle(self, for_node_id):
    handle = self.node.new_handle(for_node_id)
    handle['transaction_id'] = self.transaction_id
    return handle

  def transfer_handle(self, role_handle, for_node_id):
    handle = self.node.transfer_handle(self.role_handle_to_node_handle(role_handle), for_node_id)
    handle['transaction_id'] = self.transaction_id
    return handle

  def role_handle_to_node_handle(self, role_handle):
    return {key: value for key, value in role_handle.items() if key != 'transaction_id'}

  def spawn_enlist(self, node_config: object, participant, args: dict):
    participant_typename = self._participant_typename(participant)

    new_config = add_participant_role_to_node_config(node_config, self.transaction_id, participant_typename, args)
    self.node._controller.spawn_node(new_config)

  def _participant_typename(self, participant):
    if not issubclass(participant, ParticipantRole):
      raise errors.InternalError(f"Unrecognized participant {participant} should be a subclass of ParticipantRole")
    return participant.__name__

  def enlist(self, node_handle: object, participant, args: dict):
    participant_typename = self._participant_typename(participant)

    self.node.send(
        node_handle,
        messages.transaction.start_participant_role(
            transaction_id=self.transaction_id,
            typename=participant_typename,
            args=args,
        ))

  def send(self, role_handle, message):
    self.node.send(
        self.role_handle_to_node_handle(role_handle),
        messages.transaction.transaction_message(
            transaction_id=self.transaction_id,
            message=message,
        ))

  def deliver(self, message, sender_id):
    '''
    Deliver a message to the role.

    This method is to be called by general purpose message delivery code to indicate that a message has arrived
    for this role.
    '''
    self._matcher.deliver(message, sender_id)

  def listen(self, type):
    '''
    Return an awaitable that resolves when a particular type of message arrives for this role.
    '''
    future = self._matcher.install(type)
    return future


class _Matcher(object):
  def __init__(self):
    self._messages_by_type = defaultdict(list)
    self._future_by_type = {}

  def install(self, type):
    if self._messages_by_type[type]:
      future = asyncio.get_event_loop().create_future()
      future.set_result(self._messages_by_type[type].pop(0))
      return future
    elif type in self._future_by_type:
      raise errors.InternalError(f"A listener was already installed for messages of type \"{type}\".")
    else:
      future = asyncio.get_event_loop().create_future()
      self._future_by_type[type] = future
      return future

  def deliver(self, message, sender_id):
    type = message['type']
    if type in self._future_by_type:
      self._future_by_type.pop(type).set_result((message, sender_id))
    else:
      self._messages_by_type[type].append((message, sender_id))


class TransactionRole(object):
  '''
  Abstract base class for all transaction roles.
  '''

  async def run(self, controller: TransactionRoleController):
    '''
    Run exactly once when this `TransactionRole` instance starts to run.

    :param controller: A controller object for interacting with the overall transaction.
    :type controller: TransactionRoleController
    '''
    raise RuntimeError(f"Abstract Superclass {self.__class__}")


class OriginatorRole(TransactionRole):
  '''
  Abstract base class for `TransactionRole` instances that originate their transaction.
  '''


class ParticipantRole(TransactionRole):
  '''
  Abstract base class for `TransactionRole` instances that participate in a
  transaction originated by a separate `TransactionRole`.
  '''

  @staticmethod
  def from_config(typename: str, args: object):
    '''
    Parse a config generated by `ParticipantRole.to_config`

    :param str typename: A string identitying a particular subclass of `ParticipantRole`
    :param object arg: The kwargs arguments to pass to that subclass's initializer.

    :return: The parsed `ParticipantRole`.
    :rtype: `ParticipantRole`
    '''
    from dist_zero import all_transactions
    if typename in all_transactions.__dict__:
      result = all_transactions.__dict__[typename](**args)
      return result
    else:
      raise errors.InternalError(
          f"Unrecognized transaction type name \"{typename}\" not found in dist_zero.all_transactions.")


def add_participant_role_to_node_config(node_config, transaction_id, participant_typename, args):
  new_config = {
      'start_participant_role':
      messages.transaction.start_participant_role(
          transaction_id=transaction_id,
          typename=participant_typename,
          args=args,
      )
  }
  new_config.update(node_config)
  return new_config
